### ISSUE TITLE
Wyświetlanie wszystkich posiadłości

### ISSUE THREAD

**Issue by Asdamos** [lukdz/AgileEstate#3]
Mimo dodania posiadłości za pomocą formularza "Dodaj posiadłość" i uzyskania odpowiedzi zwrotnej informującej o pomyślnym dodaniu nowej posiadłości, strona wyświetla jedynie jedną posiadłość.

**Comment by lukdz** [comment]
W bazie danych nie pojawia się "Dodana posiadłość", problem leży w formularzu dodawania.

**Comment by lukdz** [comment]
@ref-humbold naprawił
