### ISSUE TITLE
Serwis próbuje uzyskać dostęp do zasobów sieci lokalnej !

### ISSUE THREAD

**Issue by Bozydarek** [lukdz/AgileEstate#7]
Przy próbie wejścia w szczegóły posiadłości przeglądarka próbuje połączyć się z adresem https://127.0.0.1:8000/estate/selected/1 co jest naruszeniem same-origin policy i ogólnie pojętych zasad bezpieczeństwa.

**Comment by lukdz** [comment]
Naprawione
